### ISSUE TITLE
A Problem About Experiments on Homophilous Datasets

### ISSUE THREAD

**Issue by HannieYang** [CUAI/Non-Homophily-Large-Scale#13]
Hello! I have a problem when running the code. I want to reproduce the experiments on three homophilous datasets (Cora, Citeseer and Pubmed). I tired `bash experiments/linkx_tuning.sh Cora` like the experiments on Geom-GCN datasets. But it doesn't work because there is no fixed-split files for homophilous datasets. Can you tell me how to run the experiments on these three homophilous datasets?
Thanks!

**Comment by HannieYang** [comment]
Add the details:
`Traceback (most recent call last):
  File "main.py", line 46, in <module>
    split_idx_lst = load_fixed_splits(args.dataset, args.sub_dataset)
  File "/media/ubuntu/ElementsSE/yh/Non-Homophily-Large-Scale-master/data_utils.py", line 229, in load_fixed_splits
    assert dataset in splits_drive_url.keys()
AssertionError
`
